#!/bin/sh

### BEGIN INIT INFO
# Provides:    nginx
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:        0 1 6
# Short-Description: nginx
# Description: nginx server
### END INIT INFO

#. /lib/lsb/init-functions

PROGRAM=/opt/nginx/sbin/nginx


test -x $PROGRAM || exit 0

case "$1" in
  start)
    echo "Starting Nginx server"
    /opt/nginx/sbin/nginx
    ;;
  stop)
    PID=`cat /opt/nginx/logs/nginx.pid`
    echo "Stopping Nginx server"
    if [ ! -z "$PID" ]; then
        kill -15 $PID
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: service nginx {start|stop|restart}"
    exit 1
esac

exit 0
